hello

diff --git a/dot_local/bin/fresh/testing/executable_rarbs b/dot_local/bin/fresh/testing/executable_rarbs
--- a/dot_local/bin/fresh/testing/executable_rarbs
+++ b/dot_local/bin/fresh/testing/executable_rarbs
@@ -3,6 +3,7 @@
 while getopts ":a:r:b:p:h" o; do case "${o}" in
 	h) printf "Optional arguments for custom use:\\n  -r: Dotfiles repository (local file or url)\\n  -p: Dependencies and programs csv (local file or url)\\n  -a: AUR helper (must have pacman-like syntax)\\n  -h: Show this message\\n" && exit 1 ;;
 	r) dotfilesrepo=${OPTARG} && chezmoi git ls-remote "$dotfilesrepo" || exit 1 ;;
+	r) sshdotfilesrepo=${OPTARG} && chezmoi git ls-remote "$sshdotfilesrepo" || exit 1 ;;
 	b) repobranch=${OPTARG} ;;
 	p) progsfile=${OPTARG} ;;
 	a) aurhelper=${OPTARG} ;;
@@ -10,6 +11,7 @@ while getopts ":a:r:b:p:h" o; do case "${o}" in
 esac done
 
 [ -z "$dotfilesrepo" ] && dotfilesrepo="https://github.com/romariorobby/dotfiles.git"
+[ -z "$sshdotfilesrepo" ] && sshdotfilesrepo="git@github.com:romariorobby/dotfiles.git"
 [ -z "$progsfile" ] && progsfile="https://raw.githubusercontent.com/romariorobby/dotfiles/main/private_dot_config/progs.csv"
 [ -z "$aurhelper" ] && aurhelper="paru"
 # [ -z "$repobranch" ] && repobranch="master"
@@ -58,10 +60,11 @@ getbwuser() { \
 addbwuserandpass () {
 	dialog --infobox "Adding Bitwarden-cli user \"$bwname\" for $name..." 4 50
 	[ -x "$(command -v "bw")" ] || manualinstall bitwarden-cli-bin >/dev/null 2>&1
-	bwdir="/home/$name/.local/share/bitwarden"; mkdir -p "$bwdir"; chown -R "$name":wheel "$(dirname "$bwdir")"
-	sudo -u "$name" echo $bwname > $bwdir/email
-	sudo -u "$name" echo $bwpass1 > $bwdir/key
-	sudo -u "$name" bw login $bwname $bwpass1
+	bwdir="/home/mario/.local/share/bitwarden"; mkdir -p "$bwdir"; chown -R "mario":wheel "$(dirname "$bwdir")"
+	sudo -u "mario" echo $bwname > $bwdir/email && sudo -u "mario" echo $bwpass1 > $bwdir/key
+	sudo -u "mario" bw login $(echo $bwname $bwpass1)
+	dialog --infobox "Adding Environment Variables Locally..." 4 50
+	export BW_MASTER=$(echo "$bwdir/key") && export BW_SESSION="$(bw unlock $BW_MASTER 2>/dev/null | grep 'export' | sed -E 's/.*export BW_SESSION="(.*==)"$/\1/')" || error "FAILED"
 	}
 
 preinstallmsg() { \
@@ -192,7 +195,7 @@ ntpdate 0.id.pool.ntp.org >/dev/null 2>&1
 
 adduserandpass || error "Error adding username and/or password."
 
-addbwuserandpass || error "Error adding bitwarden email and/or password."
+addbwuserandpass || error "Error adding bitwarden email and/or password is incorrect."
 
 [ -f /etc/sudoers.pacnew ] && cp /etc/sudoers.pacnew /etc/sudoers # Just in case
 
@@ -223,7 +226,7 @@ yes | sudo -u "$name" $aurhelper -S libxft-bgra-git >/dev/null 2>&1
 # Most important command! Get rid of the beep!
 systembeepoff
 
-chezgitrepo "$dotfilesrepo"
+chezgitrepo "$sshdotfilesrepo" || chezgitrepo "$dotfilesrepo"
 
 # Make zsh the default shell for the user.
 chsh -s /bin/zsh "$name" >/dev/null 2>&1
